default: &default
  app_id: fly/documentup
  config:
    sentry_url:
      fromSecret: sentry_url

development:
  <<: *default
  app_id: super-fly/documentup

test:
  <<: *default

production:
  <<: *default