config: &config
  sentry_url:
    fromSecret: sentry_url

default: &default
  app_id: fly/documentup
  config:
    <<: *config

development:
  <<: *default
  app_id: super-fly/documentup

test:
  <<: *default
  config:
    <<: *config
    sentry_url: null


production:
  <<: *default